[build]
builder = "nixpacks"
installCommand = "npm ci"
buildCommand = "bash ./build-railway-service.sh"

[deploy]
startCommand = "bash ./start-railway-service.sh"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 5

[service]
internalPort = 3000
